#image: 
#  - Visual Studio 2015
#  - Ubuntu
skip_non_tags: true

environment:
  # these variables are common to all jobs
  BUILD_OWNER: hernad
  # disable powershell on linux
  APPVEYOR_YML_DISABLE_PS_LINUX: true

  matrix:
  # - MSYS2_ARCH: x86_64
  #   MSYSTEM: MINGW64
  
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MSYS2_ARCH: i686
    MSYSTEM: MINGW32
    BUILD_ARTIFACT: windows_x86

  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    BUILD_ARTIFACT: linux_x86


only_commits:
  message: /BUILD_RELEASE/

skip_commits:
  author: /John|Jack/


platform:
  - x86

configuration:
  - Release


build_script:
- cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

- sh: '${APPVEYOR_BUILD_FOLDER}/appveyor.sh'

before_test:
# https://help.appveyor.com/discussions/questions/2356-conditionally-enable-services
#services:
#  - postgresql96
- ps: Start-Service postgresql-x64-9.6
- cmd: SET PGUSER=postgres
- cmd: SET PGPASSWORD=Password12!
- cmd: PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
- cmd: createdb F18_test

- sh: sudo apt-get remove -y libpq-dev:i386
- sh: sudo apt install -y postgresql postgresql-contrib
- sh: sudo service postgresql start
- sh: sudo -u postgres ${APPVEYOR_BUILD_FOLDER}/F18_test_db.sh
- sh: sudo apt-get install -y xvfb


test_script:  
- cmd: cd %APPVEYOR_BUILD_FOLDER%
- cmd: F18.exe -h localhost -u postgres -p Password12! -d F18_test --show-postgresql-version

- sh: LD_LIBRARY_PATH=. xvfb-run --server-args="-screen 0 1024x768x24" ./F18 -h localhost -u postgres -p Password12! -d F18_test --show-postgresql-version

on_success:
#- cmd: cd C:\
- cmd: if [%BUILD_TYPE%]==[Release] echo "SUCCESS"
- sh: echo "Ubuntu sucess :)"

artifacts: 
  # relative to build folder
  - path: F18_$(BUILD_ARTIFACT)_$(APPVEYOR_REPO_TAG_NAME).zip


deploy:
- provider: BinTray
  name: bintray hernad windows
  username: hernad
  subject: hernad
  repo: F18
  package: F18-windows-x86
  version: '$(APPVEYOR_REPO_TAG_NAME)'
  #artifact: 'hello_windows_x86_$(APPVEYOR_REPO_TAG_NAME).zip'
  api_key:
    secure: CmTociD4LaDugZgY8k5Esn0tcA1nGvV583hTrbUGmGrnBtb6B1xyArOBmFzN5TjTLuRrfB9kBNiYtqyhBf0v2HZE8uKm2cl8zGoYTU8Afb0=
  publish: true
  override: true
  on:
    appveyor_repo_tag: true
    BUILD_ARTIFACT: windows_x86

- provider: BinTray
  name: bintray hernad ubuntu
  username: hernad
  subject: hernad
  repo: F18
  package: F18-linux-x86
  version: '$(APPVEYOR_REPO_TAG_NAME)'
  #artifact: 'hello_linux_x86_$(APPVEYOR_REPO_TAG_NAME).zip'
  api_key:
    secure: CmTociD4LaDugZgY8k5Esn0tcA1nGvV583hTrbUGmGrnBtb6B1xyArOBmFzN5TjTLuRrfB9kBNiYtqyhBf0v2HZE8uKm2cl8zGoYTU8Afb0=
  publish: true
  override: true
  on:
    appveyor_repo_tag: true
    BUILD_ARTIFACT: linux_x86