trigger:
- 4
variables:
  ELECTRON_VERSION: 3.0.13

resources:
  containers:
  - container: vscode-x64
    image: joaomoreno/vscode-linux-build-agent:x64
  - container: vscode-ia32
    image: joaomoreno/vscode-linux-build-agent:ia32


jobs:
- job: Windows_x64
  pool:
    vmImage: VS2017-Win2016
  variables:
    VSCODE_ARCH: x64
  steps:
  - template: build/azure-pipelines/win32/build-win32-x64.yml

- job: Windows_ia32
  pool:
    vmImage: VS2017-Win2016
  variables:
    VSCODE_ARCH: ia32
  steps:
  - template: build/azure-pipelines/win32/build-win32-ia32.yml


- job: Linux_ia32
  pool:
    #name: Default
    vmImage: 'Ubuntu-16.04'
  # unutar containera izvrsiti operacije
  container: vscode-x64
  variables:
    BUIKD_ARCH: x64
  steps:
  - template: build/azure-pipelines/linux/build-linux.yml


- job: Linux_x64
  pool:
    #name: Default
    vmImage: 'Ubuntu-16.04'
  container: vscode-ia32
  variables:
    BUILD_ARCH: ia32
  steps:
  - template: build/azure-pipelines/linux/build-linux.yml
