trigger:
- 4

variables:
- group: API_KEYS

resources:
  containers:
  - container: vscode-x64
    image: joaomoreno/vscode-linux-build-agent:x64
  - container: vscode-ia32
    image: joaomoreno/vscode-linux-build-agent:ia32

jobs:
#- job: Windows_x64
#  pool:
#    vmImage: VS2017-Win2016
#  variables:
#    VSCODE_ARCH: x64
#  steps:
#    - script: |
#        set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
#        %CD:~0,2%\msys64\usr\bin\sed -i "s|#CacheDir.*|CacheDir=/c/Users/%USERNAME%/AppData/Local/Temp|g" /etc/pacman.conf
#        %CD:~0,2%\msys64\usr\bin\bash -lc "bash ci-build-win32.sh %CD:~0,1%"
#      displayName: CI-Build

#- job: Windows_ia32
#  pool:
#    vmImage: VS2017-Win2016
#  variables:
#    VSCODE_ARCH: ia32
#  steps:
#    - script: |
#        set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
#        %CD:~0,2%\msys64\usr\bin\sed -i "s|#CacheDir.*|CacheDir=/c/Users/%USERNAME%/AppData/Local/Temp|g" /etc/pacman.conf
#        %CD:~0,2%\msys64\usr\bin\bash -lc "bash ci-build-win32.sh %CD:~0,1%"
#      displayName: CI-Build
#      env:
#        MSYSTEM: $(MINGW_UPPER)
#        CHERE_INVOKING: yes
#        MINGW_INSTALLS: $(MINGW_LOWER)

- job: Linux_ia32
  pool:
    vmImage: 'Ubuntu-16.04'
  container: vscode-x64
  variables:
    BUILD_ARCH: ia32
    BINTRAY_ARCH: i386
  steps:
  - script: |
      ./ci-build-linux.sh
    displayName: CI-Build
    env:
      CHERE_INVOKING: yes

  - script: |
      ./upload_bintray.sh
    displayName: upload F18-linux-$(BINTRAY_ARCH) version $(BUILD.BUILDNUMBER)
    env:
      CHERE_INVOKING: yes
      BINTRAY_API_KEY: $(BINTRAY_API_KEY)


#- job: Linux_x64
#  pool:
#    vmImage: 'Ubuntu-16.04'
#  container: vscode-ia32
#  variables:
#    BUILD_ARCH: x64
#  steps:
#  - script: |
#      ./ci-build-linux.sh
#    displayName: CI-Build
#    env:
#      CHERE_INVOKING: yes

